causes:
  - No longer needed
  - Inaccurate website description
  - Item defective or doesn't work
  - Bought by mistake
  - Better price available
  - Product damaged, but shipping box OK
  - Item arrived too late
  - Missing or broken parts
  - Product and shipping box both damaged 
  - Wrong Item was sent 
  - Recieved extra item I didn't buy (what are you telling us for you good two shoes)
  - Didn't approve purchase
